# Form implementation generated from reading ui file '.\zoomplus_urlsui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets

import qrc.files  # type: ignore
from config import ZoomPlusConfig


class UiSettingsUrls(object):
    def __init__(self):
        self.cfg = ZoomPlusConfig()

    def setup_ui(self, window):
        window.setObjectName("Urls")
        window.resize(270, 490)
        window.setMinimumSize(QtCore.QSize(270, 490))
        window.setMaximumSize(QtCore.QSize(270, 490))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"C:\Users\Ryzen\PycharmProjects\zoomplus\icons\favicon.ico"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        window.setWindowIcon(icon)
        window.setStyleSheet("""QMainWindow {
    font-family: Rubik, sans-serif;
    background-color: #22222e;
}

QLineEdit {
    font-family: Rubik, sans-serif;
    background-color: #22222e;
    border: 2px solid #f66867;
    border-radius: 6px;
    color: white;
    font-size: 12pt;
    font-weight: 600;
}

QPushButton {
    color: white;
    font-family: Rubik, sans-serif;
    background-color: #fb5b5d;
    border-radius: 6px;
    font-size: 14pt;
    font-weight: 600;
}

QPushButton:pressed {
    background-color: #fa4244;
}

QLabel {
    font-family: Rubik, sans-serif;
    color: white;
    font-size: 10pt;
    font-weight: 600;
}""")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_entry = QtWidgets.QPushButton(self.centralwidget)
        self.btn_entry.setGeometry(QtCore.QRect(95, 460, 75, 20))
        self.btn_entry.setObjectName("pushButton")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(11)
        self.formLayout.setVerticalSpacing(19)
        self.formLayout.setObjectName("formLayout")

        for ind, lbl in enumerate(self.cfg.main_lbl):
            if not self.cfg.check_hide(ind):
                setattr(self, lbl, QtWidgets.QLabel(self.centralwidget))
                getattr(self, lbl).setObjectName(lbl)
                self.formLayout.setWidget(ind, QtWidgets.QFormLayout.ItemRole.LabelRole, getattr(self, lbl))

        for ind, le in enumerate(self.cfg.main_le):
            if not self.cfg.check_hide(ind):
                setattr(self, le, QtWidgets.QLineEdit(self.centralwidget))
                getattr(self, le).setAlignment(
                    QtCore.Qt.AlignmentFlag.AlignRight |
                    QtCore.Qt.AlignmentFlag.AlignTrailing |
                    QtCore.Qt.AlignmentFlag.AlignVCenter)
                getattr(self, le).setMaxLength(125)
                getattr(self, le).setObjectName(le)
                self.formLayout.setWidget(ind, QtWidgets.QFormLayout.ItemRole.FieldRole, getattr(self, le))

        self.verticalLayout.addLayout(self.formLayout)
        window.setCentralWidget(self.centralwidget)

        self.retranslate_ui(window)

        self.btn_entry.clicked.connect(self.change)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslate_ui(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("Urls", "Настройка ссылок конференций"))
        self.btn_entry.setText(_translate("Urls", 'Save'))
        self.btn_entry.setShortcut(_translate('Urls', "Return"))
        for ind, le in enumerate(self.cfg.main_le):
            if not self.cfg.check_hide(ind):
                getattr(self, le).setPlaceholderText(self.cfg.get_url_conf(ind))

        for ind, lbl in enumerate(self.cfg.main_lbl):
            if not self.cfg.check_hide(ind):
                getattr(self, lbl).setText(_translate("Urls", self.cfg.get_name_conf(ind)))

    def change(self) -> None:
        for ind, le in enumerate(self.cfg.main_le):
            if not self.cfg.check_hide(ind):
                text = getattr(self, le).text()
                if text:
                    if 'https://' in text:
                        self.cfg.set_url_conf(text, ind)
                    else:
                        window = QtWidgets.QWidget()
                        icon = QtGui.QIcon()
                        icon.addPixmap(QtGui.QPixmap(r"C:\Users\Ryzen\PycharmProjects\zoomplus\icons\favicon.ico"),
                                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                        window.setWindowIcon(icon)
                        QtWidgets.QMessageBox.warning(window, 'Некорректный ввод', 'Неправильно записаны данные '
                                                                                   'конференции')
