# Form implementation generated from reading ui file '.\ui\zoomplus_createui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import qrc.files
from config import ZoomPlusConfig


class UiCreate(object):
    def __init__(self):
        self.cfg = ZoomPlusConfig()

    def setup_ui(self, window):
        window.setObjectName("Create")
        window.resize(250, 290)
        window.setMinimumSize(QtCore.QSize(250, 290))
        window.setMaximumSize(QtCore.QSize(250, 290))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"C:\Users\Ryzen\PycharmProjects\zoomplus\icons\favicon.ico"),
                       QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        window.setWindowIcon(icon)
        window.setStyleSheet("QMainWindow {\n"
                             "    font-family: \'Rubik\', sans-serif;\n"
                             "    background-color: #22222e;\n"
                             "}\n"
                             "\n"
                             "QLineEdit {\n"
                             "    font-family: \'Rubik\', sans-serif;\n"
                             "    background-color: #22222e;\n"
                             "    border: 2px solid #f66867;\n"
                             "    border-radius: 6px;\n"
                             "    color: white;\n"
                             "    font-size: 12pt;\n"
                             "    font-weight: 600;\n"
                             "}\n"
                             "\n"
                             "QPushButton {\n"
                             "    color: white;\n"
                             "    font-family: Rubik, sans-serif;\n"
                             "    background-color: #fb5b5d;\n"
                             "    border-radius: 6px;\n"
                             "    font-size: 12pt;\n"
                             "    font-weight: 600;\n"
                             "}\n"
                             "\n"
                             "QPushButton:pressed {\n"
                             "    background-color: #fa4244;\n"
                             "}")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(60, 250, 135, 20))
        self.save.setObjectName("save")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 230, 190))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_name = QtWidgets.QLineEdit(self.widget)
        self.le_name.setObjectName("le_name")
        self.le_name.setMaxLength(16)
        self.verticalLayout.addWidget(self.le_name)
        self.le_url = QtWidgets.QLineEdit(self.widget)
        self.le_url.setObjectName("le_url")
        self.le_url.setMaxLength(125)
        self.verticalLayout.addWidget(self.le_url)
        self.reset = QtWidgets.QToolButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(220, 250, 22, 22))
        self.reset.setStyleSheet("background-color: #22222e; border: none;")
        self.reset.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(r"C:\Users\Ryzen\PycharmProjects\zoomplus\icons\reset.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reset.setIcon(icon1)
        self.reset.setIconSize(QtCore.QSize(36, 36))
        self.reset.setObjectName("reset")
        window.setCentralWidget(self.centralwidget)

        self.retranslate_ui(window)

        self.save.clicked.connect(lambda: self.save_conf(window))  # type: ignore
        self.reset.clicked.connect(lambda: self.cfg.create_data(None))  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslate_ui(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("Create", "Создание конференций"))
        self.save.setText(_translate("Create", "Save"))
        self.save.setShortcut(_translate("Create", "Return"))
        self.le_name.setPlaceholderText(_translate('Create', 'Название конференции'))
        self.le_url.setPlaceholderText(_translate('Create', 'Ссылка'))
        self.reset.setShortcut(_translate("Create", "Ctrl+Ins"))

    def save_conf(self, window) -> None:
        name_conf = self.le_name.text().title()
        url = self.le_url.text()
        if self.cfg.get_count_actual_buttons < self.cfg.limit_buttons:
            if name_conf and url and url.startswith('https://'):
                data_read = self.cfg.read_data_conf()
                for e in data_read:
                    if e['hide']:
                        e['name_conf'] = name_conf
                        e['url'] = url
                        e['hide'] = False
                        break
                self.cfg.create_data(data_read)
            else:
                QtWidgets.QMessageBox.warning(window, 'Некорректный ввод', 'Неправильно записаны данные конференции')
        else:
            QtWidgets.QMessageBox.warning(window, 'Лимит', f'Максимальное количество конференций: '
                                                           f'{self.cfg.limit_buttons}')
