# Form implementation generated from reading ui file '.\zoomplus_namesui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

__all__ = ['UiSettingsNames', 'QtCore', 'QtWidgets', 'QtGui']

from PyQt6 import QtCore, QtGui, QtWidgets

from config import ZoomPlusConfig
import qrc.files  # type: ignore


class UiSettingsNames(object):
    def setup_ui(self, window):
        window.setObjectName("ZoomPlus")
        window.resize(270, 400)
        window.setMinimumSize(QtCore.QSize(270, 400))
        window.setMaximumSize(QtCore.QSize(270, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/favicon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        window.setWindowIcon(icon)
        window.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        window.setStyleSheet("QMainWindow {\n"
                             "    background-color: #22222e;\n"
                             "    font-family: \'Rubik\', sans-serif;\n"
                             "    color: white;\n"
                             "}\n"
                             "\n"
                             "QLineEdit {\n"
                             "    font-family: Rubik, sans-serif;\n"
                             "    background-color: #22222e;\n"
                             "    border: 2px solid #f66867;\n"
                             "    font-size: 12pt;\n"
                             "    border-radius: 8px;\n"
                             "    color: white;\n"
                             "    font-weight: 800;\n"
                             "}")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(18)
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_0.setMinimumSize(QtCore.QSize(250, 25))
        self.le_0.setMaximumSize(QtCore.QSize(250, 25))
        self.le_0.setMaxLength(16)
        self.le_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_0.setObjectName("le_0")
        self.verticalLayout.addWidget(self.le_0)
        self.le_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_1.setMinimumSize(QtCore.QSize(250, 25))
        self.le_1.setMaximumSize(QtCore.QSize(250, 25))
        self.le_1.setMaxLength(16)
        self.le_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_1.setObjectName("le_1")
        self.verticalLayout.addWidget(self.le_1)
        self.le_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_2.setMinimumSize(QtCore.QSize(250, 25))
        self.le_2.setMaximumSize(QtCore.QSize(250, 25))
        self.le_2.setMaxLength(16)
        self.le_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_2.setObjectName("le_2")
        self.verticalLayout.addWidget(self.le_2)
        self.le_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_3.setMinimumSize(QtCore.QSize(250, 25))
        self.le_3.setMaximumSize(QtCore.QSize(250, 25))
        self.le_3.setMaxLength(16)
        self.le_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_3.setObjectName("le_3")
        self.verticalLayout.addWidget(self.le_3)
        self.le_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_4.setMinimumSize(QtCore.QSize(250, 25))
        self.le_4.setMaximumSize(QtCore.QSize(250, 25))
        self.le_4.setMaxLength(16)
        self.le_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_4.setObjectName("le_4")
        self.verticalLayout.addWidget(self.le_4)
        self.le_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_5.setMinimumSize(QtCore.QSize(250, 25))
        self.le_5.setMaximumSize(QtCore.QSize(250, 25))
        self.le_5.setMaxLength(16)
        self.le_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_5.setObjectName("le_5")
        self.verticalLayout.addWidget(self.le_5)
        self.le_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_6.setMinimumSize(QtCore.QSize(250, 25))
        self.le_6.setMaximumSize(QtCore.QSize(250, 25))
        self.le_6.setMaxLength(16)
        self.le_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_6.setObjectName("le_6")
        self.verticalLayout.addWidget(self.le_6)
        self.le_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_7.setMinimumSize(QtCore.QSize(250, 25))
        self.le_7.setMaximumSize(QtCore.QSize(250, 25))
        self.le_7.setMaxLength(16)
        self.le_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_7.setObjectName("le_7")
        self.verticalLayout.addWidget(self.le_7)
        self.le_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_8.setMinimumSize(QtCore.QSize(250, 25))
        self.le_8.setMaximumSize(QtCore.QSize(250, 25))
        self.le_8.setMaxLength(50)
        self.le_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_8.setObjectName("le_8")
        self.verticalLayout.addWidget(self.le_8)
        self.le_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_9.setMinimumSize(QtCore.QSize(250, 25))
        self.le_9.setMaximumSize(QtCore.QSize(250, 25))
        self.le_9.setMaxLength(16)
        self.le_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_9.setObjectName("le_9")
        self.verticalLayout.addWidget(self.le_9)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        window.setCentralWidget(self.centralwidget)

        self.retranslate_ui(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslate_ui(self, window):
        cfg = ZoomPlusConfig()
        _translate = QtCore.QCoreApplication.translate
        for ind, le in enumerate(cfg.main_le):
            getattr(self, le).setPlaceholderText(cfg.get_name_conf(ind))
        window.setWindowTitle(_translate("ZoomPlus", "Настройка названий конференций"))
