# Form implementation generated from reading ui file '.\ui\zoomplus_createui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets

import qrc.files  # type: ignore
from config import ZoomPlusConfig


class UiCreate(object):
    def __init__(self):
        self.cfg = ZoomPlusConfig()
        self.modal_windows = QtWidgets.QWidget()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"C:\Users\Ryzen\PycharmProjects\zoomplus\icons\favicon.ico"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.modal_windows.setWindowIcon(icon)

    def setup_ui(self, window):
        window.setObjectName("Create")
        window.resize(250, 290)
        window.setMinimumSize(QtCore.QSize(250, 290))
        window.setMaximumSize(QtCore.QSize(250, 290))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"C:\Users\Ryzen\PycharmProjects\zoomplus\icons\favicon.ico"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        window.setWindowIcon(icon)
        window.setStyleSheet("""QMainWindow {
    font-family: Rubik, sans-serif;
    background-color: #22222e;
}

QLineEdit {
    font-family: Rubik, sans-serif;
    background-color: #22222e;
    border: 2px solid #f66867;
    border-radius: 6px;
    color: white;
    font-size: 12pt;
    font-weight: 600;
}

QPushButton {
    color: white;
    font-family: Rubik, sans-serif;
    background-color: #fb5b5d;
    border-radius: 6px;
    font-size: 14pt;
    font-weight: 600;
}

QPushButton:pressed {
    background-color: #fa4244;
}

QLabel {
    font-family: Rubik, sans-serif;
    color: white;
    font-size: 10pt;
    font-weight: 600;
}""")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(60, 250, 135, 20))
        self.save.setObjectName("save")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 230, 190))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_name = QtWidgets.QLineEdit(self.widget)
        self.le_name.setObjectName("le_name")
        self.le_name.setMaxLength(16)
        self.verticalLayout.addWidget(self.le_name)
        self.le_url = QtWidgets.QLineEdit(self.widget)
        self.le_url.setObjectName("le_url")
        self.le_url.setMaxLength(125)
        self.verticalLayout.addWidget(self.le_url)
        self.reset = QtWidgets.QToolButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(220, 250, 22, 22))
        self.reset.setStyleSheet("background-color: #22222e; border: none;")
        # self.reset.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(r"C:\Users\Ryzen\PycharmProjects\zoomplus\icons\reset.png"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reset.setIcon(icon1)
        self.reset.setIconSize(QtCore.QSize(36, 36))
        self.reset.setObjectName("reset")
        window.setCentralWidget(self.centralwidget)

        self.retranslate_ui(window)

        self.save.clicked.connect(self.save_conf)  # type: ignore
        self.reset.clicked.connect(self.reset_buttons)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslate_ui(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("Create", "Создание конференций"))
        self.save.setText(_translate("Create", "Save"))
        self.save.setShortcut(_translate("Create", "Return"))
        self.le_name.setPlaceholderText(_translate('Create', 'Название конференции'))
        self.le_url.setPlaceholderText(_translate('Create', 'Ссылка'))
        self.reset.setShortcut(_translate("Create", "Ctrl+Ins"))

    def save_conf(self) -> None:
        name_conf = self.le_name.text().title()
        url = self.le_url.text()
        if self.cfg.get_count_actual_buttons < self.cfg.limit_buttons:
            if name_conf and url and url.startswith('https://'):
                data_read = self.cfg.read_data_conf()
                data_read.insert(0, {'name_conf': name_conf, 'url': url, 'hide': False})
                self.cfg.create_data(data_read)
            else:
                QtWidgets.QMessageBox.warning(self.modal_windows, 'Некорректный ввод', 'Неправильно записаны данные '
                                                                                       'конференции')
        else:
            QtWidgets.QMessageBox.warning(self.modal_windows, 'Лимит', f'Максимальное количество конференций: '
                                                                       f'{self.cfg.limit_buttons}')

    def reset_buttons(self) -> None:
        box = QtWidgets.QMessageBox()
        checkbox = box.information(self.modal_windows,
                                   "Обнуление всех ссылок",
                                   "Вы действительно хотите сбросить все Ваши конференции?",
                                   box.StandardButton.Ok | box.StandardButton.Cancel)
        if checkbox == 1024:
            self.cfg.create_data()
            self.cfg.create_recover()
